#!/usr/bin/env php
<?php
/**
 * Monitors incoming packets
 *
 * PHP Version 5
 *
 * <pre>
 * Scripts related to HUGnet
 * Copyright (C) 2007-2012 Hunt Utilities Group, LLC
 * Copyright (C) 2009 Scott Price
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * </pre>
 *
 * @category   Scripts
 * @package    Scripts
 * @subpackage Misc
 * @author     Scott Price <prices@hugllc.com>
 * @author     Jeff Liesmaki <jeffl@hugllc.com>
 * @copyright  2007-2012 Hunt Utilities Group, LLC
 * @copyright  2009 Scott Price
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @version    SVN: $Id$
 * @link       https://dev.hugllc.com/index.php/Project:Scripts
 *
 */
/** Packet log include stuff */
require_once 'HUGnetLib/HUGnetLib.php';

$config = HUGnetLib::Args(
    array(
        "i" => array(
            "name" => "DeviceID", "type" => "string", "args" => true
        ),
        "D" => array(
            "name" => "Data", "type" => "int", "args" => true, "default" => null
        ),
        "V" => array(
            "name" => "Value", "type" => "float", "args" => true, "default" => null
        ),
        "T" => array(
            "name" => "Toler", "type" => "float", "args" => true, "default" => null
        ),
        "c" => array(
            "name" => "Limiter", "type" => "string", "args" => true, "default" => ""
        ),
        "H" => array(
            "name" => "High", "type" => "string", "args" => true, "default" => ""
        ),
        "L" => array(
            "name" => "Low", "type" => "string", "args" => true, "default" => null
        ),
        "C" => array(
            "name" => "Control", "type" => "int", "args" => true, "default" => null
        ),
        "P" => array(
            "name" => "Process",
            "type" => "int",
            "args" => true,
            "default" => null
        ),
        "p" => array(
            "name" => "Priority",
            "type" => "int",
            "args" => true,
            "default" => null
        ),
        "S" => array(
            "name" => "Step",
            "type" => "int",
            "args" => true,
            "default" => null
        ),
    ),
    "args",
    $argv
);

$config->addLocation("/usr/share/HUGnet/config.ini");
$cli = HUGnetLib::ui($config, "CLI");
$cli->help(
    $cli->system()->get("program")."
Copyright Hunt Utilities Group, LLC
HUGnet Scripts v".trim(file_get_contents("HUGnetScripts/VERSION.TXT", true))."  "
."HUGnetLib v".$cli->system()->get("version")."

Sets the level for the level holder.

Usage: ".$cli->system()->get("program")." -i <DeviceID> -V <Value> -D <DataChannnel> [-T <tolerance>] [-v] [-f <file>]
Arguments:
    -i <DeviceID>    The device ID to use.  Should be a hex value up to 6 digits
    -P <Table>       The process table to set
    -p <Priority>    The priority to set
    -C <Channel>     The comma separated list of the control channels to set
    -S <Step>        The step size to set
    -c <DataChannel> Comma separated list of the datachannels to use for the limiters
    -H <Value>       Comma separated list of the values to hold the datachannel for the limiters
    -L <Tolerance>   Comma separated list of tolerances on the values for the limiters
    -D <DataChannel> The datachannels to use
    -V <Value>       The value to hold the datachannel at
    -T <Tolerance>   The tolerance on the value
    -v               Increment the verbosity
    -f <file>        The config file to use",
    $config->h
);
if (strlen($config->i) == 0) {
    $cli->help();
    $cli->out();
    $cli->out("DeviceID must be specified");
    exit(1);
}
if (strlen($config->P) == 0) {
    $cli->help();
    $cli->out();
    $cli->out("Process must be specified");
    exit(1);
}

$dev = $cli->system()->device(hexdec($config->i));

$process = $dev->process($config->P);
$process->pull();
$extra   = $process->get("extra");


/*
"extraText" => array(
    0 => "Priority",
    1 => "Control",
    2 => "Step",
    3 => "Data Channel 0",
    4 => "Set Point 0",
    5 => "Tolerance 0",
    6 => "Data Channel 1",
    7 => "Set Point 1",
    8 => "Tolerance 1",
    9 => "Data Channel 2",
    10 => "Set Point 2",
    11 => "Tolerance 2",
),
*/
$set = false;

if (!is_null($config->p)) {
    $extra[0] = $config->p;
    $set = true;
}
if (!is_null($config->C)) {
    $extra[1] = $config->C;
    $set = true;
}
if (!is_null($config->S)) {
    $extra[2] = $config->S;
    $set = true;
}

if (!is_null($config->D)) {
    $extra[9] = (int)$config->D;
    $set = true;
}
if (!is_null($config->V)) {
    $extra[10] = (float)$config->V;
    $set = true;
}
if (!is_null($config->T)) {
    $extra[11] = (float)$config->T;
    $set = true;
}
if (strlen($config->c)) {
    $data = explode(",", $config->c);
    $set = true;
}
if (strlen($config->H)) {
    $setpoints = explode(",", $config->H);
    $set = true;
}
if (strlen($config->L)) {
    $tolerance = explode(",", $config->L);
    $set = true;
}
for ($i = 0; $i < 2; $i++) {
    if (isset($data[$i])) {
        $extra[($i*3) + 3] = $data[$i];
        $set = true;
    }
    if (isset($setpoints[$i])) {
        $extra[($i*3) + 4] = $setpoints[$i];
        $set = true;
    }
    if (isset($tolerance[$i])) {
        $extra[($i*3) + 5] = $tolerance[$i];
        $set = true;
    }
}
if ($set) {
    $cli->out();
    $cli->out("Setting the level holder in RAM (Changes won't be saved on reboot)");

    $process->set("extra", $extra);
    if ($process->push()) {
        $cli->out("Done!");
        $cli->out(str_pad("New Setup: ", 30, " ", STR_PAD_LEFT));
    } else {
        $cli->out("Failed");
    }
} else {
    $cli->out(str_pad("Current Setup: ", 30, " ", STR_PAD_LEFT));
}
$text = $process->get("extraText");
foreach ((array)$text as $key => $text) {
    $cli->out(str_pad("$text: ", 30, " ", STR_PAD_LEFT).$extra[$key]);
}

print "Finished\n";

exit(0);

?>
