#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PW=`php -r '
    if (file_exists("/etc/hugnet/config.ini")) {
        $var = @parse_ini_file("/etc/hugnet/config.ini");
    } else {
        $var = parse_ini_file("/usr/share/HUGnet/config.ini");
    }
    echo $var["default"]["password"];
'`



echo "Setting up Mysql (enter the mysql root password)"
mysql -u root -p -vvv << EOF
CREATE DATABASE IF NOT EXISTS HUGnet; 
SET PASSWORD FOR 'HUGnet'@'localhost' = PASSWORD('${PW}');
GRANT ALL on HUGnet.* to 'HUGnet'@'localhost' IDENTIFIED BY '${PW}';
EOF


DEBPW=`sudo php -r '
    $file = file("/etc/mysql/debian.cnf");
    $line = "";
    for ($i = 0; $i < count($file); $i++) {
        if (stristr($file[$i], "password") !== false) {
            $line = trim($file[$i]);
            break;
        }
    }
    $var = explode("=", $line);
    echo trim($var[1]);
'`

if [ "${DEBPW}x" != "x" ]; then
    echo "Setting up Replication password (enter the mysql root password)"
    mysql -u root -p -vvv << EOF
    SET PASSWORD FOR 'debian-sys-maint'@'localhost' = PASSWORD('${DEBPW}');
EOF
fi



${DIR}/hugnet_pulldb
