#!/usr/bin/env php
<?php
/**
 * Monitors incoming packets
 *
 * PHP Version 5
 *
 * <pre>
 * Scripts related to HUGnet
 * Copyright (C) 2007-2012 Hunt Utilities Group, LLC
 * Copyright (C) 2009 Scott Price
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * </pre>
 *
 * @category   Scripts
 * @package    Scripts
 * @subpackage Misc
 * @author     Scott Price <prices@hugllc.com>
 * @author     Jeff Liesmaki <jeffl@hugllc.com>
 * @copyright  2007-2012 Hunt Utilities Group, LLC
 * @copyright  2009 Scott Price
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @version    SVN: $Id$
 * @link       https://dev.hugllc.com/index.php/Project:Scripts
 *
 */
/** Packet log include stuff */
require_once 'HUGnetLib/HUGnetLib.php';

$config = HUGnetLib::Args(
    array(
        "i" => array("name" => "DeviceID", "type" => "string", "args" => true),
        "C" => array(
            "name" => "Control", "type" => "int", "args" => true, "default" => null
        ),
        "D" => array(
            "name" => "Data", "type" => "int", "args" => true, "default" => 0
        ),
    ),
    "args",
    $argv
);

$config->addLocation("/usr/share/HUGnet/config.ini");
$cli = HUGnetLib::ui($config, "CLI");
$cli->help(
    $cli->system()->get("program")."
Copyright Hunt Utilities Group, LLC
HUGnet Scripts v".trim(file_get_contents("HUGnetScripts/VERSION.TXT", true))."  "
."HUGnetLib v".$cli->system()->get("version")."

Sends a series of DAC set packets to HUGnetLab endpoints.

Usage: ".$cli->system()->get("program")." -i <DeviceID> -C <Channel> -D <Value> [-v] [-f <file>]
Arguments:
    -i <DeviceID>   The device ID to use.  Should be a hex value up to 6 digits
    -C <Channel>    The control channel to set
    -D <Value>      The value to set it to
    -v              Increment the verbosity
    -f <file>       The config file to use",
    $config->h
);
if (strlen($config->i) == 0) {
    $cli->help();
    $cli->out();
    $cli->out("DeviceID must be specified");
    exit(1);
}
if (is_null($config->C)) {
    $cli->help();
    $cli->out();
    $cli->out("Channel must be specified");
    exit(1);
}

$data = "";
for ($i = 0; $i < 4; $i++) {
    $data .= sprintf("%02X", ($config->D >> ($i * 8)) & 0xFF);
}

$dev = $cli->system()->device(hexdec($config->i));

$pkt = $dev->action()->send(
    array(
        "Command" => '0x64',
        "Data" => sprintf("%02X", $config->C).$data,
    )
);
if (is_object($pkt)) {
    $reply = $pkt->Reply();
    if (is_null($reply)) {
        print "No Reply\r\n";
    } else if (!empty($reply)) {
        if ($reply == $data) {
            $cli->out("Done!");
        } else {
            $cli->out("Failure!!!!");
        }
    } else {
        print "Empty Reply\r\n";
    }
} else {
    $cli->out("No Reply");
}


print "Finished\n";

exit(0);
?>
