#!/usr/bin/env php
<?php
/**
 * Tests, serializes, and loads bootloader into HUGnetLab endpoints
 *
 * PHP Version 5
 *
 * List below are the objectives for this PHP script:
 *    I.   Initialize the JTAG emulator
 *    II.  Load and run test firmware
 *           A. Test Serial number has been fixed in the test program
 *              itself to 0x000020.
 *           B. Initial test is simple response to a ping.
 *    III. Program endpoint with serial number and hardware version
 *           A. This will be done through a command to test firmware
 *              which will cause a flash_write to the correct location.
 *    IV.  Load the bootloader program
 *           A. This should use current 003937boot install program.cfg
 *
 *
 *
 * <pre>
 * Scripts related to HUGnet
 * Copyright (C) 2007-2012 Hunt Utilities Group, LLC
 * Copyright (C) 2009 Scott Price
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * </pre>
 *
 * @category   Scripts
 * @package    Scripts
 * @subpackage Test
 * @author     Jeff Liesmaki <jeffl@hugllc.com>
 * @copyright  2007-2012 Hunt Utilities Group, LLC
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @version    SVN: $Id$
 * @link       https://dev.hugllc.com/index.php/Project:Scripts
 */
 

/* ===========  Includes =============== */
require_once 'HUGnetLib/HUGnetLib.php';
require_once 'HUGnetScripts/EndpointTest.php';

$config = HUGnetLib::Args(array(), "args", $argv);
$config->addLocation("/usr/share/HUGnet/config.ini");

$cli =  \HUGnet\processes\EndpointTest::factory($config);


$cli->help(
    $cli->system()->get("program")."
Copyright Hunt Utilities Group, LLC
HUGnet Scripts v".trim(file_get_contents("HUGnetScripts/VERSION.TXT", true))."  "
."HUGnetLib v".$cli->system()->get("version")."

Tests, serializes, and loads bootloader for HUGnet Endpoints.

Usage: ".$cli->system()->get("program")." [-v] [-f <file>] 
Arguments:
    -v              Increment the verbosity
    -f <file>       The config file to use",
    $config->h
);

$cli->main();
exit(EXIT_SUCCESS);







?>
