#!/usr/bin/env php
<?php
/**
 * Firmware release tests for endpoints using HUGnetOS
 *
 * PHP Version 5
 *
 * List below are the objectives for this PHP script:
 *    I.   Initialize the firmware release test system
 *    II.  Load release bootloader and application firmware
 *    III. Test release bootloader and application firmware
 *    IV.  Log test results.
 *
 *
 * <pre>
 * Scripts related to HUGnet
 * Copyright (C) 2007-2012 Hunt Utilities Group, LLC
 * Copyright (C) 2009 Scott Price
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * </pre>
 *
 * @category   Scripts
 * @package    Scripts
 * @subpackage Test
 * @author     Jeff Liesmaki <jeffl@hugllc.com>
 * @copyright  2007-2016 Hunt Utilities Group, LLC
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @version    SVN: $Id$
 * @link       https://dev.hugllc.com/index.php/Project:Scripts
 */
 

/* ===========  Includes =============== */
require_once 'HUGnetLib/HUGnetLib.php';
require_once 'HUGnetScripts/FirmwareTest.php';

$config = HUGnetLib::Args(array(), "args", $argv);
$config->addLocation("/usr/share/HUGnet/config.ini");

$cli =  \HUGnet\processes\FirmwareTest::factory($config);


$cli->help(
    $cli->system()->get("program")."
Copyright Hunt Utilities Group, LLC
HUGnet Scripts v".trim(file_get_contents("HUGnetScripts/VERSION.TXT", true))."  "
."HUGnetLib v".$cli->system()->get("version")."

Loads, tests and logs results for release firmware for HUGnet Endpoints.

Usage: ".$cli->system()->get("program")." [-v] [-f <file>] 
Arguments:
    -v              Increment the verbosity
    -f <file>       The config file to use",
    $config->h
);

$cli->main();
exit(EXIT_SUCCESS);







?>
